name: FirebasePipeline

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy next js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          python -c "import os; file = open('.service-account.json', 'w'); file.write(os.environ['GOOGLE_APPLICATION_CREDENTIALS']); file.close()"
          npm install -g firebase-tools
          # yarn
          ls
          cat service-account.json
          # yarn build
          # export GOOGLE_APPLICATION_CREDENTIALS="/service-account.json"
          # firebase deploy --only hosting:$FIREBASE_TARGET_HOSTING
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_TARGET_HOSTING: ${{ secrets.FIREBASE_TARGET_HOSTING }}

