name: FirebasePipeline

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy next js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          npm install -g firebase-tools
          echo 'after install'
          yarn
          echo 'after install Dependecies'
          ls
          yarn build
          echo 'after build'
          firebase deploy --only hosting:$FIREBASE_TARGET_HOSTING
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_TARGET_HOSTING: ${{ secrets.FIREBASE_TARGET_HOSTING }}

