name: FirebasePipeline

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy next js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          base64-encoded-secret: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          filename: "service-account.json"
          is-executable: true
          working-directory: "."
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - run: |
          printf $GOOGLE_APPLICATION_CREDENTIALS >> "service-account.json"
          npm install -g firebase-tools
          yarn
          ls
          yarn build
          export GOOGLE_APPLICATION_CREDENTIALS="/service-account.json"
          firebase deploy --only hosting:$FIREBASE_TARGET_HOSTING
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_TARGET_HOSTING: ${{ secrets.FIREBASE_TARGET_HOSTING }}

