name: FirebasePipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build next js
    runs-on: node-alpine
    steps:
      - name: Install Dependecies
        run: |
            npm install -g firebase-tools
            cp $FIREBASE_SERVICE_ACCOUNT "$PWD/service-account.json"
            export GOOGLE_APPLICATION_CREDENTIALS="$PWD/service-account.json"
            yarn
            yarn build
  deploy:
    name: Deploy Firebase
    runs-on: node-alpine
    needs: [ build]
    steps:
      - name: Deploy Firebase Hosting
        run: |
            firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:$FIREBASE_TARGET_HOSTING