name: FirebasePipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build next js
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Install Dependecies
        env:
            FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
            npm install -g firebase-tools
            cp $FIREBASE_SERVICE_ACCOUNT "$PWD/service-account.json"
            export GOOGLE_APPLICATION_CREDENTIALS="$PWD/service-account.json"
            yarn
            yarn build
  deploy:
    name: Deploy Firebase
    runs-on: ubuntu-latest
    needs: [ build]
    steps:
      - name: Deploy Firebase Hosting
        env:
            FIREBASE_TARGET_HOSTING: ${{ secrets.FIREBASE_TARGET_HOSTING }}
        run: |
            firebase deploy --only hosting:$FIREBASE_TARGET_HOSTING